---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: database
    namespace: {{ .ReleaseNamespace }}
spec:
    accessModes:
        - ReadWriteOnce
    volumeMode: Filesystem
    resources:
        requests:
            storage: 1Gi
    storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: app
    namespace: {{ .ReleaseNamespace }}
spec:
    accessModes:
        - ReadWriteOnce
    volumeMode: Filesystem
    resources:
        requests:
            storage: 1Gi
    storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: backups
    namespace: {{ .ReleaseNamespace }}
spec:
    accessModes:
        - ReadWriteOnce
    volumeMode: Filesystem
    resources:
        requests:
            storage: 1Gi
    storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: config
    namespace: {{ .ReleaseNamespace }}
spec:
    accessModes:
        - ReadWriteOnce
    volumeMode: Filesystem
    resources:
        requests:
            storage: 10Mi
    storageClassName: local-path
