apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ttrss.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: postgres
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app: db
  clusterIP: None
