{{- $appName := "app" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ttrss.labels" . | nindent 4 }}
    app: {{ $appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ttrss.selectorLabels" . | nindent 6 }}
      app: {{ $appName }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ttrss.selectorLabels" . | nindent 8 }}
        app: {{ $appName }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $appName }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: cthulhoo/ttrss-fpm-pgsql-static
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: "/var/www/html"
              name: app
            - mountPath: "/opt/tt-rss/config.d"
              name: config
              readOnly: true
          ports:
            - name: apphttp
              containerPort: 9000
              protocol: TCP
          env:
            - name: TTRSS_SELF_URL_PATH
              value: "http://{{ .Values.host }}/tt-rss/"
            - name: TTRSS_DB_USER
              value: {{ .Values.database.username }}
            - name: TTRSS_DB_NAME
              value: {{ .Values.database.database }}
            - name: TTRSS_DB_PASS
              valueFrom:
                secretKeyRef:
                    name: ttrss-database
                    key: password
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: apphttp
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: apphttp
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: app
          persistentVolumeClaim:
            claimName: app
        - name: config
          persistentVolumeClaim:
            claimName: config
            readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
