apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "power-sensor-monitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "power-sensor-monitor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "power-sensor-monitor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "power-sensor-monitor.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "kc0bfv/power_sensor_monitor"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: "/opt/webhook_data"
              name: {{ include "power-sensor-monitor.fullname" . }}
          ports:
            - name: althttp
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /webhook/version/
              port: althttp
          readinessProbe:
            httpGet:
              path: /webhook/version/
              port: althttp
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: PORT
              value: "8080"
            - name: URL_BASE
              value: "webhook"
            - name: WRITE_DIR
              value: "/opt/webhook_data"
            - name: WRITE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "power-sensor-monitor.fullname" . }}
                  key: writekey
            - name: READ_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "power-sensor-monitor.fullname" . }}
                  key: readkey
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "power-sensor-monitor.fullname" . }}
          persistentVolumeClaim:
            claimName: {{ include "power-sensor-monitor.fullname" . }}
