apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ include "power-sensor-monitor.fullname" . }}
    namespace: {{ .Release.Namespace }}
spec:
    accessModes:
        - ReadWriteOnce
    volumeMode: Filesystem
    resources:
        requests:
            storage: 100Mi
    storageClassName: local-path
