{{- $secret := (lookup "v1" "Secret" .Release.Namespace (include "funkwhale.fullname" .)) -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "funkwhale.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "funkwhale.name" . }}
    helm.sh/chart: {{ include "funkwhale.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  CACHE_URL: {{ include "funkwhale.redisUrl" . | b64enc }}
  DATABASE_URL: {{ include "funkwhale.dbUrl" . | b64enc }}
  {{ if $secret -}}
  DJANGO_SECRET_KEY: {{ (.Values.djangoSecret | default (b64dec $secret.data.DJANGO_SECRET_KEY)) | b64enc }}
  {{ else -}}
  DJANGO_SECRET_KEY: {{ (.Values.djangoSecret | default uuidv4) | b64enc }}
  {{ end }}

{{- range $key, $val := .Values.extraSecret }}
  {{ $key }}: {{ $val | b64enc }}
{{- end }}
