---
apiVersion: v2
name: funkwhale
description: A social platform to enjoy and share music
icon: https://funkwhale.audio/favicon.png
appVersion: "1.4.0"

type: application
version: 1.1.0-alpha
dependencies:
  - name: postgresql
    version: ^12.1.4
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: ^17.3.17
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
